# Generated by Django 5.1.6 on 2025-03-20 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_gastos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gastos',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
