# Generated by Django 5.1.6 on 2025-03-20 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_gastos_descricao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gastos',
            old_name='data',
            new_name='dataGasto',
        ),
    ]
