# Generated by Django 5.1.6 on 2025-03-20 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_data_gastos_datagasto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gastos',
            old_name='nome',
            new_name='titulo',
        ),
    ]
