# Generated by Django 5.1.6 on 2025-03-21 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_nome_gastos_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gastos',
            name='dataGasto',
            field=models.DateField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='gastos',
            name='descricao',
            field=models.TextField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='gastos',
            name='horario',
            field=models.TimeField(blank=True, default=False, null=True),
        ),
    ]
